# Generated by Django 5.2.16 on 2026-07-10 01:21

import apps.tickets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.tickets.models.ticket_attachment_upload_path, verbose_name='文件')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='文件类型')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='文件大小')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket', verbose_name='所属工单')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '工单附件',
                'verbose_name_plural': '工单附件',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket', '-created_at'], name='tickets_tic_ticket__73df30_idx'), models.Index(fields=['uploaded_by', '-created_at'], name='tickets_tic_uploade_3d4e78_idx')],
            },
        ),
    ]
