# Generated by Django 5.2.16 on 2026-07-10 01:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_tickets', to=settings.AUTH_USER_MODEL, verbose_name='关注人'),
        ),
    ]
