# Generated by Django 5.2.16 on 2026-07-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_watchers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='名称')),
                ('color', models.CharField(default='#64748b', max_length=20, verbose_name='颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工单标签',
                'verbose_name_plural': '工单标签',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='tickets_tic_name_bab360_idx')],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='tickets.tickettag', verbose_name='标签'),
        ),
    ]
