# Generated by Django 5.2.16 on 2026-07-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_tickettag_ticket_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='close_reason',
            field=models.TextField(blank=True, verbose_name='关闭原因'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reopen_reason',
            field=models.TextField(blank=True, verbose_name='重开原因'),
        ),
    ]
