# Generated by Django 5.2.16 on 2026-07-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('comment', '评论'), ('status_change', '状态流转'), ('assign', '分配处理人')], max_length=30, verbose_name='动作'),
        ),
    ]
