# Generated by Django 5.2.16 on 2026-07-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('comment', '评论'), ('status_change', '状态流转'), ('assign', '分配处理人'), ('remind', '催办'), ('feedback', '评价')], max_length=30, verbose_name='动作'),
        ),
    ]
