# Generated by Django 5.2.16 on 2026-07-09 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ticket_assigned', '工单分配'), ('ticket_commented', '工单评论'), ('ticket_status_changed', '状态变更')], max_length=40, verbose_name='通知类型')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('message', models.TextField(verbose_name='内容')),
                ('target_type', models.CharField(blank=True, max_length=80, verbose_name='目标类型')),
                ('target_id', models.CharField(blank=True, max_length=80, verbose_name='目标 ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['target_type', 'target_id', '-created_at'], name='notificatio_target__16e7c9_idx')],
            },
        ),
    ]
