# Generated by Django 5.2.16 on 2026-07-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ticket_assigned', '工单分配'), ('ticket_commented', '工单评论'), ('ticket_status_changed', '状态变更'), ('ticket_reminded', '工单催办')], max_length=40, verbose_name='通知类型'),
        ),
    ]
