# Generated by Django 5.2.16 on 2026-07-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ticket_assigned', '工单分配'), ('ticket_commented', '工单评论'), ('ticket_status_changed', '状态变更'), ('ticket_reminded', '工单催办'), ('ticket_priority_changed', '优先级变更'), ('ticket_feedback_submitted', '工单评价')], max_length=40, verbose_name='通知类型'),
        ),
    ]
